# -*- coding: utf-8 -*-
"""HOPE_Demo_ULTRA_STABLE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXCZadJB14pqA5d5tgGo3UzQ2B_DTnyR

# Nano-HOPE: Open source Implementation

**Author:** Shushank  
**Architecture:** Self-Modifying Titans + Continuum Memory
"""

# @title Installation
!pip install -q tiktoken datasets matplotlib tqdm

# @title Imports & Setup
import os
import time
import math
import gc
import torch
import torch.nn as nn
import torch.nn.functional as F
import tiktoken
import matplotlib.pyplot as plt
from tqdm import tqdm
from datasets import load_dataset
from torch.utils.data import DataLoader, IterableDataset
from dataclasses import dataclass
from typing import Optional, Tuple, List

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# @title Config
@dataclass
class HOPEConfig:
    vocab_size: int = 50257
    n_embd: int = 384  # Reduced for Colab to 384 if premium use 768
    n_head: int = 6    # coolab free - 6 premium - 12 for better
    n_layer: int = 6   # same 6 or 12
    block_size: int = 256  # Context window - 256/512
    dropout: float = 0.1
    bias: bool = False

config = HOPEConfig()
print(f"Model size: ~{(config.n_layer * config.n_embd**2 * 12) / 1e6:.1f}M parameters")

"""### HOPEModel Definition (Transformer Decoder-only with Continuum Memory) This defines the core architecture, including `MultiHeadAttention`, `FeedForward`, and `Block` modules, composing them into the `HOPEModel`. The `forward` method is designed to accept and return `states` to facilitate "continuum memory" across batches, as implied by the training and generation loops."""

class LayerNorm(nn.Module):
    """ LayerNorm but with an optional bias. PyTorch's LayerNorm doesn't support bias=False """
    def __init__(self, ndim, bias):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(ndim))
        self.bias = nn.Parameter(torch.zeros(ndim)) if bias else None

    def forward(self, input):
        return F.layer_norm(input, self.weight.shape, self.weight, self.bias, 1e-5)

class MultiHeadAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        assert config.n_embd % config.n_head == 0
        # key, query, value projections for all heads, but in a batch
        self.c_attn = nn.Linear(config.n_embd, 3 * config.n_embd, bias=config.bias)
        # output projection
        self.c_proj = nn.Linear(config.n_embd, config.n_embd, bias=config.bias)
        # regularization
        self.attn_dropout = nn.Dropout(config.dropout)
        self.resid_dropout = nn.Dropout(config.dropout)
        self.n_head = config.n_head
        self.n_embd = config.n_embd
        self.dropout = config.dropout
        # not really a 'bias', but more of a mask, but following the OpenAI/HF naming convention
        self.register_buffer("bias", torch.tril(torch.ones(config.block_size, config.block_size))
                                    .view(1, 1, config.block_size, config.block_size))

    def forward(self, x):
        B, T, C = x.size() # batch size, sequence length, embedding dimensionality (n_embd)

        # calculate query, key, values for all heads in batch and move head forward to be the batch dim
        q, k, v = self.c_attn(x).split(self.n_embd, dim=2)
        k = k.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)
        q = q.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)
        v = v.view(B, T, self.n_head, C // self.n_head).transpose(1, 2) # (B, nh, T, hs)

        # attention (B, nh, T, hs) x (B, nh, hs, T) -> (B, nh, T, T)
        att = (q @ k.transpose(-2, -1)) * (1.0 / math.sqrt(k.size(-1)))
        att = att.masked_fill(self.bias[:,:,:T,:T] == 0, float('-inf'))
        att = F.softmax(att, dim=-1)
        att = self.attn_dropout(att)
        y = att @ v # (B, nh, T, T) x (B, nh, T, hs) -> (B, nh, T, hs)
        y = y.transpose(1, 2).contiguous().view(B, T, C) # re-assemble all head outputs side by side

        # output projection
        y = self.resid_dropout(self.c_proj(y))
        return y

class FeedForward(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(config.n_embd, 4 * config.n_embd, bias=config.bias),
            nn.GELU(),
            nn.Linear(4 * config.n_embd, config.n_embd, bias=config.bias),
            nn.Dropout(config.dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.ln_1 = LayerNorm(config.n_embd, bias=config.bias)
        self.attn = MultiHeadAttention(config)
        self.ln_2 = LayerNorm(config.n_embd, bias=config.bias)
        self.mlp = FeedForward(config)

    def forward(self, x):
        x = x + self.attn(self.ln_1(x))
        x = x + self.mlp(self.ln_2(x))
        return x

class HOPEModel(nn.Module):
    def __init__(self, config):
        super().__init__()
        assert config.vocab_size is not None
        assert config.block_size is not None
        self.config = config

        self.transformer = nn.ModuleDict(dict(
            wte = nn.Embedding(config.vocab_size, config.n_embd),
            wpe = nn.Embedding(config.block_size, config.n_embd),
            drop = nn.Dropout(config.dropout),
            h = nn.ModuleList([Block(config) for _ in range(config.n_layer)]),
            ln_f = LayerNorm(config.n_embd, bias=config.bias),
        ))
        self.lm_head = nn.Linear(config.n_embd, config.vocab_size, bias=False)

        # initialize all weights
        self.apply(self._init_weights)
        # apply special scaled init to the residual projections, per GPT-2 paper
        for pn, p in self.named_parameters():
            if pn.endswith('c_proj.weight'):
                torch.nn.init.normal_(p, mean=0.0, std=0.02/math.sqrt(2 * config.n_layer))

        print(f"Number of parameters: {self.get_num_params()/1e6:.2f}M")

    def get_num_params(self, non_embedding=True):
        """
        Return the number of parameters in the model.
        For non-embedding count it excludes token embeddings and positional embeddings.
        """
        n_params = sum(p.numel() for p in self.parameters())
        if non_embedding:
            n_params -= self.transformer.wpe.weight.numel()
        return n_params

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None, states=None):
        device = idx.device
        b, t = idx.size()
        assert t <= self.config.block_size, f"Cannot forward sequence of length {t}, block size is only {self.config.block_size}"
        pos = torch.arange(0, t, dtype=torch.long, device=device) # shape (t)

        # forward the GPT model itself
        tok_emb = self.transformer.wte(idx) # token embeddings of shape (b, t, n_embd)
        pos_emb = self.transformer.wpe(pos) # position embeddings of shape (t, n_embd)
        x = self.transformer.drop(tok_emb + pos_emb)

        new_states = []
        for i, block in enumerate(self.transformer.h):
            if states is not None and states[i] is not None:
                # This is a placeholder for 'continuum memory' / recurrent state
                # A more sophisticated implementation might involve specific fusion mechanisms
                # or modifications to attention/FFN blocks.
                # For now, a simple residual connection from the previous state is used.
                x = x + states[i].to(device) # Ensure state is on the correct device
            x = block(x)
            new_states.append(x) # Store current output as new state

        x = self.transformer.ln_f(x)

        if targets is not None:
            # if we are given some targets also calculate the loss
            logits = self.lm_head(x)
            loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1), ignore_index=-1)
        else:
            # inference-time mini-optimization: only forward the lm_head on the very last position
            logits = self.lm_head(x[:, [-1], :]) # note: using list [-1] to preserve the time dim
            loss = None

        return logits, loss, new_states

# Model Instantiation
model = HOPEModel(config).to(device)
print("✓ HOPEModel instantiated and moved to device.")

# @title CRITICAL FIX: Compile the model (DISABLED)
# if hasattr(torch, 'compile'):
#     print("Compiling model with torch.compile (6-10x speedup)...")
#     model = torch.compile(model)
#     print("✓ Compilation enabled")
# else:
print("⚠ torch.compile is disabled by user request.")

# @title Streaming Dataset (Memory Efficient)
class StreamingTextDataset(IterableDataset):
    def __init__(self, split="train", block_size=256): #<-- change to 256 for light use
        self.dataset = load_dataset("roneneldan/TinyStories", split=split, streaming=True)
        self.tokenizer = tiktoken.get_encoding("gpt2")
        self.block_size = block_size

    def __iter__(self):
        buffer = []
        for item in self.dataset:
            tokens = self.tokenizer.encode(item['text'])
            buffer.extend(tokens)
            while len(buffer) >= self.block_size + 1:
                chunk = buffer[:self.block_size + 1]
                buffer = buffer[self.block_size:]
                x = torch.tensor(chunk[:-1], dtype=torch.long)
                y = torch.tensor(chunk[1:], dtype=torch.long)
                yield x, y

train_dataset = StreamingTextDataset(split="train", block_size=config.block_size)
train_loader = DataLoader(train_dataset, batch_size=4)
print("✓ Streaming dataset ready (batch_size=4 for Colab)")

# @title Training Loop (STATEFUL + AMP)
# from torch.cuda.amp import autocast, GradScaler  # Disabled

# Hyperparameters
max_iters = 10000 #<-- if increassed better training but took more time
learning_rate = 1e-4 #<-- don't set too high learning rate i did and get error.
min_lr = 3e-5
warmup_iters = 200
grad_clip = 1.0

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=0.1)
# scaler = GradScaler()  # Disabled

def get_lr(it):
    if it < warmup_iters:
        return learning_rate * it / warmup_iters
    if it > max_iters:
        return min_lr
    decay_ratio = (it - warmup_iters) / (max_iters - warmup_iters)
    coeff = 0.5 * (1.0 + math.cos(math.pi * decay_ratio))
    return min_lr + coeff * (learning_rate - min_lr)

# CRITICAL FIX: Persistent states
persistent_states = None
loss_history = []

model.train()
train_iter = iter(train_loader)
pbar = tqdm(range(max_iters), desc="Training")

for step in pbar:
    lr = get_lr(step)
    for param_group in optimizer.param_groups:
        param_group['lr'] = lr

    try:
        X, Y = next(train_iter)
    except StopIteration:
        train_iter = iter(train_loader)
        X, Y = next(train_iter)

    X, Y = X.to(device), Y.to(device)

    # CRITICAL FIX: Detach states BEFORE forward pass to prevent graph accumulation
    if persistent_states is not None:
        persistent_states = [s.detach().clone() if s is not None else None for s in persistent_states]


    # CRITICAL FIX: Pass states across batches
    # CRITICAL FIX: Autocast disabled to prevent freeze
    # with autocast():
    #     logits, loss, new_states = model(X, Y, states=persistent_states)

    # Direct forward pass (no autocast)
    logits, loss, new_states = model(X, Y, states=persistent_states)

    # Detach states to prevent backprop through time explosion
    persistent_states = [s.detach() if s is not None else None for s in new_states]

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(model.parameters(), grad_clip)
    optimizer.step()

    loss_history.append(loss.item())
    pbar.set_postfix({'loss': f'{loss.item():.4f}', 'lr': f'{lr:.2e}'})

    # CRITICAL FIX: Periodic memory cleanup
    if step % 100 == 0:
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

    # Reset states periodically to prevent drift
    if step % 500 == 0 and step > 0:
        persistent_states = None
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()
        print(f"\n[Step {step}] Memory reset - CUDA cache cleared")

print("\n✓ Training complete!")
plt.figure(figsize=(10, 4))
plt.plot(loss_history)
plt.title("Training Loss (Stateful)")
plt.xlabel("Step")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

# @title CRITICAL FIX: True Stateful Generation
@torch.no_grad()
def generate_stateful(model, prompt, max_tokens=200, temperature=0.8):
    model.eval()
    tokenizer = tiktoken.get_encoding("gpt2")
    tokens = torch.tensor(tokenizer.encode(prompt), dtype=torch.long, device=device).unsqueeze(0)

    # Prefill: process prompt once
    logits, _, states = model(tokens)
    next_token = torch.multinomial(F.softmax(logits[0, -1] / temperature, dim=-1), 1)
    tokens = torch.cat([tokens, next_token.unsqueeze(0)], dim=1)

    # Generation: O(1) per token
    for _ in range(max_tokens - 1):
        logits, _, states = model(next_token.unsqueeze(0), states=states)
        next_token = torch.multinomial(F.softmax(logits[0, -1] / temperature, dim=-1), 1)
        tokens = torch.cat([tokens, next_token.unsqueeze(0)], dim=1)

    return tokenizer.decode(tokens[0].tolist())

prompt = "Once upon a time,"
print("Prompt:", prompt)
print("\n" + "="*60)
print(generate_stateful(model, prompt, max_tokens=150))
print("="*60)